if: branch =~ ^(master|dev|feature\/.*)$ AND commit_message !~ /auto\/ci:\sset\sversion/
language: node_js
node_js:
  - "14.15"
git:
  depth: false
cache:
  directories:
    - node_modules
script:
  - git checkout $TRAVIS_BRANCH
  - git remote set-url origin https://$USER:$GITHUB_API_KEY@github.com/eigen-space/codestyle.git
  - yarn lint && yarn test:ci
  - yarn build && npm run deploy:publish;
before_install:
  - echo "registry=https://$REGISTRY/" >> .npmrc
  - echo "//$REGISTRY/:_authToken=$ACCESS_TOKEN" >> .npmrc
