language: node_js
node_js:
  - "11.10"
git:
  depth: false
# node_modules cache
cache:
  directories:
    - node_modules
if: branch = master

jobs:
  include:
    - if: ./node_modules/@eigenspace/helper-scripts/scripts/ci/detect-autocommit.sh
    - stage: setup
      script:
        - chmod +x ./node_modules/@eigenspace/helper-scripts/scripts/ci/detect-autocommit.sh
        - git checkout $TRAVIS_BRANCH
        - git remote set-url origin https://sergeevNick:$GITHUB_API_KEY@github.com/eigen-space/codestyle.git
    - stage: build
      script: yarn build
    - stage: deploy
      script: npm run deploy:publish

stages:
  - setup
  - build
  - deploy