language: node_js
node_js:
  - "11.10"
git:
  depth: false
cache:
  directories:
    - node_modules
script:
  - git checkout $TRAVIS_BRANCH
  - git remote set-url origin https://$USER:$GITHUB_API_KEY@github.com/eigen-space/codestyle.git
  - cat src/scripts/credentials/google-sheets-credentials.json
  - yarn build && yarn script:extract-rules-meta-info-to-google-sheets
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_ACCESS_TOKEN}" > .npmrc
  - echo "${GOOGLE_SHEETS_CREDENTIALS}" > src/scripts/credentials/google-sheets-credentials.json
notifications:
  slack:
    rooms:
      - eigenspaceworkspace:kmQErenC9R4KA4kWyb1j8UaS#ci
    on_success: change
    on_failure: always
