language: node_js
node_js:
  - "11.10"
git:
  depth: false
# node_modules cache
cache:
  directories:
    - node_modules
if: branch = master

before_script: chmod +x ./node_modules/@eigenspace/helper-scripts/scripts/ci/detect-autocommit.sh

jobs:
  include:
    - if: ./node_modules/@eigenspace/helper-scripts/scripts/ci/detect-autocommit.sh
    - stage: build
      script: yarn build
    - stage: deploy
      script: npm run deploy:publish

stages:
  - build
  - deploy